version: '3.9'

services:
  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keyshade_db
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - keyshade-dev
  web:
    container_name: keyshade-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - keyshade-dev
  api:
    container_name: keyshade-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - keyshade-dev

networks:
  keyshade-dev:
    driver: bridge
